### ISSUE TITLE
Feature: CICD 구성

### ISSUE THREAD

**Issue by lcomment** [najasin/na-jasin-be#11]
## Description

> CICD를 구성한다.

## To-do

- ec2 및 rds 환경 세팅
  - [x] ec2에 docker 및 nginx 설치
  - [x] nginx 프록시 구성
  - [x] ec2, rds 보안 그룹 설정
- [x] ec2에 도메인 연결 (api.na-jasin.com)
- [x] dockerfile 작성
- [x] github actions yml 파일 작성
- [x] appspec.yml 파일 작성
- [x] deploy.sh 파일 작성
- [x] s3 및 codedeploy 구성
- [x] Cors 설정
