### ISSUE TITLE
Feature: 기본 설정 및 global  Bean 구현

### ISSUE THREAD

**Issue by lcomment** [najasin/na-jasin-be#2]
## Description

> 개발에 필요한 기본적인 설정(config)와 global Bean을 구현한다.

## To-do

- [x] Query Dsl 설정
- [x] Jpa Audit 설정
- [x] 공통 응답 포멧 dto 구현
- [x] 로깅 aop 구현
- [x] Spring Security 설정
