### ISSUE TITLE
Feature: #20 내적 나사, 마이페이지, 타인페이지 api 구현

### ISSUE THREAD

**Issue by adoo24** [najasin/na-jasin-be#23]
## Description

> description
내적 나사 api 구현 
## To-do

- [x] 사용 설명서 조회
- [x] 사용 설명서 생성
- [x] 마이페이지 조회
- [x] 마이페이지 수정
- [x] 타인 페이지 조회
- [x] 타인 페이지 작성
- [x] 캐릭터 전체 아이템 조회

## ETC
닉네임 attribute가 comment엔 있는데 user에 없네요...빠르게 고쳐보겠습니다 -> 수정하였습니다!
